[package]
name = "redox-ecc"
version = "0.1.0"
authors = ["Armando Faz Hernandez"]
edition = "2018"
description = "elliptic curve arithmetic"
keywords = ["elliptic curve", "math"]

[[bench]]
name = "uno"
harness = false

[dependencies]
bencher = "0.1.5"
num-bigint = "0.2"
num-traits = "0.2.11"
