name: Rustico

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building
      run: cargo build --verbose
    - name: Testing
      run: cargo test --verbose
